[package]
name = "habit_server"
version = "0.1.0"
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2018"

[dependencies]
sha3 = "0.9.1"
serde = "1.0.126"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
